---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: loki
data:
  default.conf: |-
    server {
      listen 80 default_server;
      server_name _;
      location / {
              proxy_set_header Host $host;
              #proxy_set_header Authorization "Basic YWRtaW46cHJvbS1vcGVyYXRvcg=="; # to generate the token use this - echo -n "admin:prom-operator" | base64 -w 0
              #proxy_pass https://grafana.18.215.199.234.nip.io:30443/;
              proxy_set_header Authorization "Basic YWRtaW46dVpONWV1N2RkN0tQd2FuSTQ0MWJCUGpvdWRKOHc3NEVHcTU3OTdYNg=="; # to generate the token use this - echo -n "admin:prom-operator" | base64 -w 0
              proxy_pass http://loki-grafana:80/;
              proxy_pass_header Authorization;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_ssl_verify off;
              proxy_ssl_server_name on;
              proxy_hide_header X-Frame-Options;
              add_header X-Frame-Options "ALLOWALL";
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_pass_request_headers on;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
      }
      
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-proxy
  namespace: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-proxy
  template:
    metadata:
      labels:
        app: grafana-proxy
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: default.conf
              path: default.conf
      containers:
        - name: grafana-proxy
          image: docker.io/library/nginx:1.21.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf 
              subPath: default.conf      

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-proxy
  name: grafana-proxy
  namespace: loki
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
  selector:
    app: grafana-proxy
  type: ClusterIP
