namespace: sample-microservice
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- product.yaml
- shipment.yaml
- nginx-config-map.yaml
- frontend.yaml
- ingress.yaml
# - repocreds.yaml
images:
- name: ghcr.io/junaid18183/frontend_microservice_react
  newName: ghcr.io/junaid18183/frontend_microservice_react
  newTag: sha-0e703c4
- name: ghcr.io/junaid18183/product_microservice_sample
  newName: ghcr.io/junaid18183/product_microservice_sample
  newTag: sha-078e010
- name: ghcr.io/junaid18183/shipment_microservice_sample
  newName: ghcr.io/junaid18183/shipment_microservice_sample
  newTag: sha-9351a27
