apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
- github.com/junaid18183/gitops_kube_manifests/argo-workflows?ref=main
# - github.com/junaid18183/gitops_kube_manifests/argo-events?ref=main